spring.application.name=ipl.com

# Oracle DB Connection
spring.datasource.url=jdbc:oracle:thin:@//10.20.5.8:1524/ORCL18DB
spring.datasource.username=TRAINING3
spring.datasource.password=TRAINING3
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true